apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dandelion.fullname" . }}-config
  labels:
    app: {{ include "dandelion.fullname" . }}
data:
  LOGGING_ENDPOINT: {{ include "fluent-bit.fullname" . }}-fluent-bit
  LOGGING_PORT: {{ .Values.config.LOGGING_PORT | quote }}

