apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dandelion.fullname" . }}
  labels:
    app: {{ include "dandelion.fullname" . }}
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    {{- if .Values.annotations.deployment }}
    {{- toYaml .Values.annotations.deployment | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      app: {{ include "dandelion.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "dandelion.fullname" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      securityContext:
        {{- if .Values.securityContext.enabled }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
        runAsGroup: {{ .Values.securityContext.runAsGroup }}
        fsGroup: {{ .Values.securityContext.fsGroup }}
        {{- end }}
      containers:
      - name: {{ include "dandelion.fullname" . }}-container
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          privileged: true
        ports:
        - containerPort: {{ .Values.service.port }}
          name: http
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
        envFrom:
        - configMapRef:
            name: {{ include "dandelion.fullname" . }}-config

